### ISSUE TITLE
The authenticity of host 'github.com (64:ff9b::14cd:f3a6)' can't be established on npm install

### ISSUE THREAD

**Issue by okeaditya988** [ovvn/dom-to-pdf#19]
![Screenshot_20220118_163224](https://user-images.githubusercontent.com/54762542/149909982-9314a22d-b7f5-4a6d-bfdb-1fcc6dbeaff7.png)

**Comment by ovvn** [comment]
Hi @okeaditya988, try the latest version 0.2.9, also what's your node/npm version?

**Comment by okeaditya988** [comment]
hi @ovvn, the latest version 0.2.9, it's work. thanks
