### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by johan-ansink** [ovvn/dom-to-pdf#2]
the dependency url 
"dom-to-image": "git://github.com/dmapper/dom-to-image",
does not exist. it should be
https://github.com/tsayen/dom-to-image

**Comment by omazin** [comment]
The dependency works fine and the public fork https://github.com/dmapper/dom-to-image exists.
Check the npm documentation https://docs.npmjs.com/files/package.json#git-urls-as-dependencies.

**Comment by ovvn** [comment]
The dependency works fine and the public fork https://github.com/dmapper/dom-to-image exists.
Check the npm documentation https://docs.npmjs.com/files/package.json#git-urls-as-dependencies.
