### ISSUE TITLE
In the PDF, design is not continuous

### ISSUE THREAD

**Issue by nagoorbilal** [ovvn/dom-to-pdf#21]
In the PDF design is not continuous ,in the page 1 of file there is a space available for Second div, but the second div doesn't continuously show below the first div, second div starts in second page from top by leaving space below first div in first page.

<div id="divPdfReport" >
<div id='div1'> //it takes height of 15% in page 1
<img src={headerimg} />  
 </div>

<div id='div2'> // by leaving empty space of 85% (HEIGHT) this div start from second page
 // table  
 </div>

</div>

**Comment by ovvn** [comment]
Hi, sounds like the div's height is more than the 85% of the first page's free space, try to split the div into parts.

**Comment by nagoorbilal** [comment]
![Page 1](https://user-images.githubusercontent.com/49015393/183356404-7a919a43-e6ac-4c16-89bb-044c6b4f41fa.jpg)
![Page 2](https://user-images.githubusercontent.com/49015393/183356420-a7315c31-6f31-48e3-b2e3-c3c00ef65170.jpg)

design not continuous, i have given sample screenshot

**Comment by nagoorbilal** [comment]
design is not continuous, i giving sample pdf below
[Sample.pdf](https://github.com/ovvn/dom-to-pdf/files/9279457/Sample.pdf)

**Comment by ovvn** [comment]
Yes, like I said above, the table block takes the whole page's height, it simply doesn't fit within the first page's free space hence it's shifted to the second page. That's an intended behaviour.

**Comment by nagoorbilal** [comment]
OK, if any possibility to resolve this problem, i need the table div start from first page..

**Comment by ovvn** [comment]
Yes, you would need to split the table into parts. For instance, into two divs or each row can be a separate div.
