### ISSUE TITLE
Image is not displaying in PDF

### ISSUE THREAD

**Issue by nagoorbilal** [ovvn/dom-to-pdf#22]
` <div id="divPdfReport" ref={pdfref} className='pdfPaged1' > <img src={ClientRight} style={{width:'160px'}}/> </div>`

 var element = document.getElementById('divPdfReport');
            
             domToPdf(element, function(pdf) {
             console.log('done');
          });

**Comment by nagoorbilal** [comment]
[imgnotdisplaying.pdf](https://github.com/ovvn/dom-to-pdf/files/9348624/imgnotdisplaying.pdf)

The Image is showing in browser but not showing in pdf

**Comment by ovvn** [comment]
How does the image source look like, is `ClientRight` a path to image? Is the image stored on a different domain? Do you see CORS errors in a browser console when downloading a pdf?

**Comment by nagoorbilal** [comment]
There is no console error while downloading pdf ,i have import ClientRight image as well
The issue is still there can you give any solution...

**Comment by ovvn** [comment]
Try to specify a path to the image (e.g. http://your-domain.com/image.jpg) or base64 encoded string as the image source.

**Comment by nagoorbilal** [comment]
yes, it's working on base64 format , Thanks @ovvn
