### ISSUE TITLE
Can't copy text from pdf

### ISSUE THREAD

**Issue by tisufa** [ovvn/dom-to-pdf#28]
Hello, i have an issue, after i download that pdf. I can't copy text from that pdf. Can help me? thank you

**Comment by ovvn** [comment]
Hey, you need some OCR tool, e.g. https://tools.pdf24.org/en/ocr-pdf

**Comment by tisufa** [comment]
> Hey, you need some OCR tool, e.g. https://tools.pdf24.org/en/ocr-pdf

Thank you for your respond, i think this awesome package have an option to enable/disabled copy from .pdf.
