### ISSUE TITLE
Trouble getting image to appear in PDF

### ISSUE THREAD

**Issue by votemike** [ovvn/dom-to-pdf#4]
I am embedding an image within the container that I am rendering out to PDF. The image src is "blob:http://localhost:3000/8700bb63-c31e-45fe-98fc-499479dca412". However it is not appearing in the PDF.
I don't think the problem is CORS, so I don't think I need a proxy URL.
Is this something wrong with my implementation? Or something wrong with dom-to-pdf?

**Comment by harsh-syook** [comment]
@votemike you can check this https://github.com/harsh-syook/dom-to-pdf i also had same issue so i forked and made some changes now it works

**Comment by ovvn** [comment]
looks like the image's src isn't correct.

**Comment by votemike** [comment]
> looks like the image's src isn't correct.

In what way is the image's src not correct?

**Comment by ovvn** [comment]
@votemike in a way it’s not being handled by the dom-to-image renderer.
Try to specify a path to the image (e.g. `http://localhost/image.jpg`) or base64 encoded string as the image source.
