### ISSUE TITLE
Error TypeError: Assignment to read-only properties is not allowed in strict mode in React App because jspdf on MS EDGE v 44.x.x

### ISSUE THREAD

**Issue by jrmarqueshd** [ovvn/dom-to-pdf#5]
Hey i'm using experimental this lib, but, i get a bug in jspdf dependencie.

I'm report this to jspdf lib creator, but iI thought it was cool to warn you here about the bug too, so you can follow the status of the error updates. 

link to issue from jspdf library: https://github.com/MrRio/jsPDF/issues/2843

**Comment by ovvn** [comment]
Hi @jrmarqueshd
jsPDF library was updated, perhaps you could test again to see if the issue persists?
