### ISSUE TITLE
Save the pdf in a server

### ISSUE THREAD

**Issue by IagoJDiniz** [ovvn/dom-to-pdf#7]
I'd like to know if there is a way to store the generated PDF on the server(I'm willing to turn it into base64 and save in the server).

**Comment by dvwright** [comment]
This is a front-end library, it works within the dom on the client browser. You need a library which works server side. If you are using a node webserver, such as [express](https://expressjs.com/), take a look at [pdfkit](https://pdfkit.org).

**Comment by omazin** [comment]
As @dvwright pointed out, this is a client-side library. @IagoJDiniz You can try [puppeteer](https://github.com/puppeteer/puppeteer) on the server.
