### ISSUE TITLE
Styling the PDF

### ISSUE THREAD

**Issue by rash09** [ovvn/dom-to-pdf#8]
How do we add styling to the PDF file like margins, header, footer, images, etc

**Comment by dvwright** [comment]
This library generates a PDF based on the displayed client side html. Style the html page as you want the PDF to look. (Think of it like a 'screenshot' of your page). If you need more control over the PDF directly, maybe take a look into [jspdf](https://www.npmjs.com/package/jspdf) or [pdfkit](https://pdfkit.org/)
